### ISSUE TITLE
actor_widget segfault on reply.

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1283]
Hi, I've got a Qt QOJECT derived from the caf actor_widget mixin, it works nicely, but I've just discovered that if it tries to reply to a message the application segfaults.

To clarify it receives the message okay, it just dies after it returns the response.

Has this behaviour been tested ? The example chat demo, doesn't respond to messages, they just trigger actions.

I can build caf with debug if required. But it's possible responding is not allowed or is easily checked via the demo.

(Using 0.18.4)

Handler in mixin.
```
    set_message_handler([=](actor_companion * /*self_*/) -> message_handler {
    return {
        [=](shotgun_acquire_secret_atom) -> std::string {
            return "the message";
        }
    };});
```

gdb output.
```

(gdb) where
#0  0x00007ffff62fbca0 in caf::actor_system::scheduler() () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#1  0x00007ffff640444d in caf::scoped_execution_unit::exec_later(caf::resumable*) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#2  0x00007ffff63ef03a in caf::scheduled_actor::enqueue(std::unique_ptr<caf::mailbox_element, std::default_delete<caf::mailbox_element> >, caf::execution_unit*) ()
   from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#3  0x00007ffff62f564f in caf::actor_control_block::enqueue(std::unique_ptr<caf::mailbox_element, std::default_delete<caf::mailbox_element> >, caf::execution_unit*) ()
   from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#4  0x00007ffff63ee032 in void caf::detail::profiled_send<caf::local_actor, caf::actor_control_block*, caf::intrusive_ptr<caf::actor_control_block>, caf::message>(caf::local_actor*, caf::actor_control_block*&&, caf::intrusive_ptr<caf::actor_control_block> const&, caf::message_id, std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >, caf::execution_unit*, caf::message&&) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#5  0x00007ffff63ed2d8 in caf::response_promise::state::deliver_impl(caf::message) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#6  0x00007ffff63ed570 in caf::response_promise::respond_to(caf::local_actor*, caf::mailbox_element*, caf::message&) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#7  0x00007ffff7d7b7dd in caf::detail::invoke_result_visitor::operator()<std::string> (this=0x7ffffffee580)
    at /builds/actor_framework/0.18.4/20920e4c5c/include/caf/detail/invoke_result_visitor.hpp:54
#8  0x00007ffe402bf5f8 in caf::detail::default_behavior_impl<std::tuple<xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(xstudio::shotgun_client::shotgun_acquire_secret_atom)>, xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(const caf::group_down_msg&)> >, caf::detail::dummy_timeout_definition>::<lambda(auto:29&)>::operator()<xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(xstudio::shotgun_client::shotgun_acquire_secret_atom)> >(xstudio::ui::qml::ShotgunDataSourceUI::<lambda(caf::actor_companion*)>::<lambda(xstudio::shotgun_client::shotgun_acquire_secret_atom)> &) const (this=0x7ffffffee510, fun=...)
    at /builds/actor_framework/0.18.4/20920e4c5c/include/caf/detail/behavior_impl.hpp:129
#9  0x00007ffe402bf784 in caf::detail::default_behavior_impl<std::tuple<xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(xstudio::shotgun_client::shotgun_acquire_secret_atom)>, xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(const caf::group_down_msg&)> >, caf::detail::dummy_timeout_definition>::invoke_impl<0, 1>(caf::detail::invoke_result_visitor &, caf::message &, std::index_sequence) (this=0x33b5250, f=..., msg=...)
    at /builds/actor_framework/0.18.4/20920e4c5c/include/caf/detail/behavior_impl.hpp:135
#10 0x00007ffe402bf483 in caf::detail::default_behavior_impl<std::tuple<xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(xstudio::shotgun_client::shotgun_acquire_secret_atom)>, xstudio::ui::qml::ShotgunDataSourceUI::init(caf::actor_system&)::<lambda(caf::actor_companion*)>::<lambda(const caf::group_down_msg&)> >, caf::detail::dummy_timeout_definition>::invoke(caf::detail::invoke_result_visitor &, caf::message &) (this=0x33b5250, f=..., xs=...) at /builds/actor_framework/0.18.4/20920e4c5c/include/caf/detail/behavior_impl.hpp:111
#11 0x00007ffff63f5a1f in caf::scheduled_actor::consume(caf::mailbox_element&) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#12 0x00007ffff63f5dd5 in caf::scheduled_actor::reactivate(caf::mailbox_element&) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#13 0x00007ffff63f5ec3 in caf::scheduled_actor::activate(caf::execution_unit*, caf::mailbox_element&) () from /builds/actor_framework/0.18.4/20920e4c5c/lib64/libcaf_core.so.0.18.4
#14 0x0000000000a90b9a in caf::mixin::actor_object<QObject, 32337>::event (this=0x33b8a80, event=0x7fffc80284b0) at ../include/xstudio/ui/qml/actor_object.hpp:82
#15 0x00007ffff58396ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Widgets.so.5
#16 0x00007ffff5841ed8 in QApplication::notify(QObject*, QEvent*) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Widgets.so.5
#17 0x00007fffeea4abba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#18 0x00007fffeea4d2f1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#19 0x00007fffeeaa12a3 in ?? () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#20 0x00007fffea58dc45 in g_main_dispatch (context=0x7ffe740016e0) at gmain.c:3176
#21 g_main_context_dispatch (context=context@entry=0x7ffe740016e0) at gmain.c:3829
#22 0x00007fffea58dfb0 in g_main_context_iterate (context=context@entry=0x7ffe740016e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3902
#23 0x00007fffea58e03f in g_main_context_iteration (context=0x7ffe740016e0, may_block=1) at gmain.c:3963
#24 0x00007fffeeaa096e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#25 0x00007fffeea4992b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#26 0x00007fffeea5133c in QCoreApplication::exec() () from /builds/qt/5.15.3/9275812bd9/lib/libQt5Core.so.5
#27 0x0000000000898566 in main (argc=1, argv=0x7fffffff0368) at ../src/launch/xstudio/src/xstudio.cpp:651

```

**Comment by Neverlord** [comment]
> Has this behaviour been tested ?

I don't think the Qt bindings had been extensible tested. However, from the stack trace it looks like the responding itself isn't the issue since it dies when accessing the scheduler. Could it be a lifetime issue with the actor system?

**Comment by alatdneg** [comment]
Lifetime of which objects though ? None of the actors are temporary and I'm not passing objects that might be destroyed in flight. Bit stumped, I'll try running with memory sanity checks to see if that shows any funnies.

**Comment by Neverlord** [comment]
This kind of bug is usually easy to track down with ASAN builds. 🙂

**Comment by Neverlord** [comment]
@alatdneg did you get more details from ASAN or other sanity checkers?

**Comment by alatdneg** [comment]
Not had a chance yet, as I've been on holiday. I'll get back to you once
I've tested it.

**Comment by alatdneg** [comment]
Well I'm stumped I can't reproduce the problem anymore. I must have accidentally fixed the real issue ?
Thanks for your help.
