### ISSUE TITLE
SEGFAULT in new uniform_type test

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#276]
Jenkins occasionally is running into a SEGFAULT with the new unit testing framework [1]. The bug is reproducable on inet151 with GDB:

```
(gdb) bt
#0  0x00007ffff6808cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff680c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6845f24 in __libc_message (do_abort=1, fmt=fmt@entry=0x7ffff69546c8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6853ac6 in malloc_printerr (ptr=0xf5de1f, str=0x7ffff695083a "malloc(): memory corruption", action=<optimized out>) at malloc.c:4996
#4  _int_malloc (av=0x7ffff6b91760 <main_arena>, bytes=537) at malloc.c:3447
#5  0x00007ffff6855340 in __GI___libc_malloc (bytes=537) at malloc.c:2891
#6  0x00007ffff702af2d in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff70863b9 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7086f7b in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7087014 in std::string::reserve(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7065386 in std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff70695a6 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff7060db5 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00000000008329f1 in caf::test::logger::stream::operator<< (this=0x7fffffffd8f0, str=...)
    at /var/lib/jenkins/data/workspace/CAF/develop branch logging/label_exp/Linux && clang && LeakSanitizer/libcaf_test/caf/test/unit_test_impl.hpp:176
#14 0x0000000000834222 in caf::test::engine::run (colorize=false, log_file=..., verbosity_console=5, verbosity_file=3, suites_str=..., not_suites_str=..., tests_str=..., 
    not_tests_str=...) at /var/lib/jenkins/data/workspace/CAF/develop branch logging/label_exp/Linux && clang && LeakSanitizer/libcaf_test/caf/test/unit_test_impl.hpp:422
#15 0x0000000000835fa1 in main (argc=6, argv=0x7fffffffe528)
    at /var/lib/jenkins/data/workspace/CAF/develop branch logging/label_exp/Linux && clang && LeakSanitizer/libcaf_test/caf/test/unit_test_impl.hpp:615
```

@Hamdor are you on it?

[1] http://mobi39.cpt.haw-hamburg.de/job/CAF/job/develop%20branch%20logging/label_exp=Linux%20&&%20clang%20&&%20LeakSanitizer/72/consoleFull

**Comment by Hamdor** [comment]
Im on it :p
Am 24.04.2015 11:21 vorm. schrieb Dominik Charousset <notifications@github.com>:

**Comment by Neverlord** [comment]
I can no longer reproduce this after porting all unit tests to the new fixtures. 10k runs on inet151 went by without segfault.
