### ISSUE TITLE
Potential memory leak in node_id::deserialize()

### ISSUE THREAD

**Issue by tobim** [actor-framework/actor-framework#905]
I'm experiencing a leak in a unit test in VAST that originates from `node_id`:
```
Direct leak of 240 byte(s) in 6 object(s) allocated from:
    #0 0x7fbbac2a724f in operator new(unsigned long) (/nix/store/9xphqdzxsiwcln9hpkc3hs88jvjhk29k-gcc-9.1.0-lib/lib/libasan.so.5+0x10c24f)
    #1 0x7fbba639f354 in caf::node_id::deserialize(caf::deserializer&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/node_id.cpp:216
    #2 0x7fbba639f540 in caf::inspect(caf::deserializer&, caf::node_id&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/node_id.cpp:227
    #3 0x1f2bce6 in std::enable_if<caf::detail::is_inspectable<caf::deserializer, caf::node_id>::value&&(!caf::detail::has_serialize<caf::node_id, std::is_pointer<caf::node_id>::value||std::is_function<caf::node_id>::value>::value), decltype (inspect((declval<caf::deserializer&>)(), (declval<caf::node_id&>)()))>::type caf::data_processor<caf::deserializer>::apply<caf::node_id>(caf::node_id&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/data_processor.hpp:468
    #4 0x2176763 in std::enable_if<(!caf::meta::is_annotation<caf::node_id&>::value)&&(!caf::is_allowed_unsafe_message_type<caf::node_id&>::value), caf::error>::type caf::data_processor<caf::deserializer>::operator()<caf::node_id&, unsigned long&>(caf::node_id&, unsigned long&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/data_processor.hpp:520
    #5 0x21735b2 in auto vast::system::inspect<caf::deserializer>(caf::deserializer&, vast::system::actor_identity&) /home/tobim/tenzir/vast/libvast/vast/system/replicated_store.hpp:99
    #6 0x21768aa in std::enable_if<caf::detail::is_inspectable<caf::deserializer, vast::system::actor_identity>::value&&(!caf::detail::has_serialize<vast::system::actor_identity, std::is_pointer<vast::system::actor_identity>::value||std::is_function<vast::system::actor_identity>::value>::value), decltype (inspect((declval<caf::deserializer&>)(), (declval<vast::system::actor_identity&>)()))>::type caf::data_processor<caf::deserializer>::apply<vast::system::actor_identity>(vast::system::actor_identity&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/data_processor.hpp:468
    #7 0x2173688 in std::enable_if<(!caf::meta::is_annotation<vast::system::actor_identity&>::value)&&(!caf::is_allowed_unsafe_message_type<vast::system::actor_identity&>::value), caf::error>::type caf::data_processor<caf::deserializer>::operator()<vast::system::actor_identity&>(vast::system::actor_identity&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/data_processor.hpp:520
    #8 0x217bb5c in caf::detail::type_erased_value_impl<vast::system::actor_identity>::load(caf::deserializer&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/detail/type_erased_value_impl.hpp:79
    #9 0x7fbba6371a7a in caf::message::load(caf::deserializer&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/message.cpp:142
    #10 0x1f2c7fc in std::enable_if<caf::deserializer::writes_state, void>::type caf::serialize<caf::deserializer>(caf::deserializer&, caf::type_erased_tuple&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/type_erased_tuple.hpp:232
    #11 0x1f2c2eb in decltype (serialize({parm#1}, {parm#2})) caf::detail::delegate_serialize<caf::deserializer, caf::message>(caf::deserializer&, caf::message&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/detail/delegate_serialize.hpp:65
    #12 0x1f2be2d in std::enable_if<(!std::is_empty<caf::message>::value)&&caf::detail::has_serialize<caf::message, std::is_pointer<caf::message>::value||std::is_function<caf::message>::value>::value, caf::error>::type caf::data_processor<caf::deserializer>::apply<caf::message>(caf::message&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/data_processor.hpp:402
    #13 0x7fbbaa8dfb42 in std::enable_if<std::is_same<caf::error, decltype ((((declval<caf::deserializer&>)()).apply)((declval<caf::message&>)()))>::value, void>::type caf::operator&<caf::message>(caf::deserializer&, caf::message&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/deserializer.hpp:60
    #14 0x7fbbaa8d479e in std::enable_if<std::is_same<caf::error, decltype ((((declval<caf::deserializer&>)()).apply)((declval<caf::message&>)()))>::value, caf::deserializer&>::type caf::operator>><caf::message>(caf::deserializer&, caf::message&) (/home/tobim/tenzir/vast/build/lib/libvast.so.0+0x32f779e)
    #15 0x7fbbaa89ce62 in deliver<caf::stateful_actor<vast::system::raft::server_state> > /home/tobim/tenzir/vast/libvast/src/system/raft.cpp:388
    #16 0x7fbbaa8aab24 in advance_commit_index<caf::stateful_actor<vast::system::raft::server_state> > /home/tobim/tenzir/vast/libvast/src/system/raft.cpp:404
    #17 0x7fbbaa8894a4 in operator() /home/tobim/tenzir/vast/libvast/src/system/raft.cpp:1065
    #18 0x7fbbaa8c3483 in operator()<caf::atom_constant<(caf::atom_value)285885514842795626>&, caf::message&> /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/match_case.hpp:76
    #19 0x7fbbaa8c2823 in apply_args<caf::lfinvoker<false, vast::system::raft::consensus(caf::stateful_actor<vast::system::raft::server_state>*, vast::path)::<lambda(vast::system::replicate_atom, const caf::message&)> >, 0, 1, caf::detail::pseudo_tuple<caf::atom_constant<(caf::atom_value)285885514842795626>, caf::message> > /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/detail/apply_args.hpp:38
    #20 0x7fbbaa8bf5b7 in invoke /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/match_case.hpp:164
    #21 0x7fbba6229dc6 in caf::detail::behavior_impl::invoke(caf::detail::invoke_result_visitor&, caf::type_erased_tuple&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/behavior_impl.cpp:102
    #22 0x7fbba622909f in invoke /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/behavior_impl.cpp:35
    #23 0x7fbba623d117 in caf::behavior::operator()(caf::detail::invoke_result_visitor&, caf::type_erased_tuple&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/caf/behavior.hpp:109
    #24 0x7fbba63ee81e in caf::scheduled_actor::consume(caf::mailbox_element&) /home/tobim/tenzir/vast/aux/caf/libcaf_core/src/scheduled_actor.cpp:711
...
```

The client code is located here: https://github.com/tenzir/vast/blob/daf8a34778d9585ade9d6ea4e6dcd900efcee997/libvast/vast/system/replicated_store.hpp#L99
Note that this happens only with gcc. It could be a false positive or user error, but I wanted to let you know about it in case this turns out to be an issue in caf. I`ll try to reproduce it with a smaller example soon.

**Comment by mavam** [comment]
@tobim, does this patch fix the issue:

```
diff --git a/libcaf_core/src/node_id.cpp b/libcaf_core/src/node_id.cpp
index 915e95c2..55bad16b 100644
--- a/libcaf_core/src/node_id.cpp
+++ b/libcaf_core/src/node_id.cpp
@@ -213,7 +213,7 @@ error node_id::deserialize(deserializer& source) {
   }
   if (impl == atom("default")) {
     if (data_ == nullptr || data_->implementation_id() != atom("default"))
-      data_.reset(new default_data);
+      data_.reset(new default_data, false);
     return data_->deserialize(source);
   }
   return sec::unknown_type;
```

**Comment by tobim** [comment]
It does indeed, thanks for looking into it.
For the record: this it not a gcc only issue. I didn't find it with clang because the leak check is disabled by default on macOS.

**Comment by mavam** [comment]
Glad to see this worked. Let's wait for @Neverlord for the final sanity checking.

**Comment by Neverlord** [comment]
✅ Sane

Thanks for reporting *and* fixing! 🙂
